CREATE TABLE IF NOT EXISTS feeder_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name VARCHAR(100) NOT NULL,
    domain_name VARCHAR(100) NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    project_id VARCHAR(100) NOT NULL,
    board_id INTEGER NOT NULL CHECK (board_id > 0),
    CONSTRAINT uq_feeder_project UNIQUE (domain_name, stream_name, project_id, board_id)
);
